### ISSUE TITLE
Azure scan fails due to unable initializing image struct

### ISSUE THREAD

**Issue by KEINOS** [KEINOS/Dockerfile_of_SQLite3#25]
- Error message:

```text
Error: FATAL unable to initialize a image struct: failed to initialize source: reading manifest test in docker.io/keinos/sqlite3: manifest unknown: manifest unknown
Error: An error occurred while scanning the container image for best practice violations
```
- Detailed log: https://github.com/KEINOS/Dockerfile_of_SQLite3/actions/runs/2728452311
- Possible cause: https://github.com/Azure/container-scan/issues/146
  - Reff: https://github.com/goodwithtech/dockle/issues/188

**Comment by KEINOS** [comment]
Adding the below to [the workflow](https://github.com/KEINOS/Dockerfile_of_SQLite3/blob/master/.github/workflows/azure_scan.yml) fixed the issue:

```YAML
env:
  # See:
  # https://github.com/goodwithtech/dockle/issues/188
  # https://github.com/Azure/container-scan/issues/146
  DOCKLE_HOST: "unix:///var/run/docker.sock"
```
- [See diff](https://github.com/KEINOS/Dockerfile_of_SQLite3/pull/26/files)

Closing #25 by PR #26
